title: Julien Corioland
description: 'Software Engineer @ Microsoft - Azure, Containers and DevOps'
url: "https://blog.jcorioland.io"
show_downloads: false
permalink: /archives/:year/:month/:day/:title.html
twitter:
  username: jcorioland
logo: /assets/images/profile.jpg
image: /assets/images/profile.jpg
social:
  name: Julien Corioland
  links:
    - https://twitter.com/jcorioland
    - https://www.linkedin.com/in/juliencorioland
    - https://github.com/jcorioland

excerpt_separator: <!--more-->
google_analytics: UA-124844581-1

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman 
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

version: 1.0
paginate: 5
paginate_path: "/archives/page/:num/"
  